export function getFlagEmoji(teamName: string): string {
  const lowerName = teamName.toLowerCase().trim();

  // Custom manual mappings for all teams in the database
  const nameToCode: Record<string, string> = {
    "afghanistan": "AF",
    "albania": "AL",
    "algeria": "DZ",
    "andorra": "AD",
    "angola": "AO",
    "argentina": "AR",
    "armenia": "AM",
    "aruba": "AW",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belarus": "BY",
    "Belgium": "BE",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bermuda": "BM",
    "bolivia": "BO",
    "bosnia & herzegovina": "BA",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "brazil": "BR",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "cabo verde": "CV",
    "cape verde": "CV",
    "cameroon": "CM",
    "canada": "CA",
    "central african republic": "CF",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "colombia": "CO",
    "comoros": "KM",
    "congo republic": "CG",
    "congo": "CG",
    "costa rica": "CR",
    "croatia": "HR",
    "cuba": "CU",
    "curaçao": "CW",
    "curacao": "CW",
    "cyprus": "CY",
    "czechia": "CZ",
    "czech republic": "CZ",
    "côte d'ivoire": "CI",
    "ivory coast": "CI",
    "dr congo": "CD",
    "democratic republic of the congo": "CD",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominican republic": "DO",
    "ecuador": "EC",
    "egypt": "EG",
    "el salvador": "SV",
    "equatorial guinea": "GQ",
    "estonia": "EE",
    "eswatini": "SZ",
    "ethiopia": "ET",
    "faroe islands": "FO",
    "fiji": "FJ",
    "finland": "FI",
    "france": "FR",
    "gabon": "GA",
    "gambia": "GM",
    "georgia": "GE",
    "germany": "DE",
    "ghana": "GH",
    "gibraltar": "GI",
    "greece": "GR",
    "grenada": "GD",
    "guadeloupe": "GP",
    "guatemala": "GT",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "honduras": "HN",
    "hong kong": "HK",
    "hungary": "HU",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "jamaica": "JM",
    "japan": "JP",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kosovo": "XK",
    "kuwait": "KW",
    "kyrgyzstan": "KG",
    "latvia": "LV",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luxembourg": "LU",
    "madagascar": "MG",
    "malawi": "MW",
    "malaysia": "MY",
    "mali": "ML",
    "malta": "MT",
    "martinique": "MQ",
    "mauritania": "MR",
    "mauritius": "MU",
    "mexico": "MX",
    "moldova": "MD",
    "montenegro": "ME",
    "montserrat": "MS",
    "morocco": "MA",
    "mozambique": "MZ",
    "myanmar": "MM",
    "namibia": "NA",
    "netherlands": "NL",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "north korea": "KP",
    "north macedonia": "MK",
    "norway": "NO",
    "oman": "OM",
    "palestine": "PS",
    "panama": "PA",
    "paraguay": "PY",
    "peru": "PE",
    "philippines": "PH",
    "poland": "PL",
    "portugal": "PT",
    "puerto rico": "PR",
    "qatar": "QA",
    "romania": "RO",
    "russia": "RU",
    "rwanda": "RW",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint martin": "MF",
    "samoa": "WS",
    "san marino": "SM",
    "saudi arabia": "SA",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapore": "SG",
    "sint maarten": "SX",
    "slovakia": "SK",
    "slovenia": "SI",
    "solomon islands": "SB",
    "somalia": "SO",
    "south africa": "ZA",
    "south korea": "KR",
    "south sudan": "SS",
    "spain": "ES",
    "sudan": "SD",
    "suriname": "SR",
    "sweden": "SE",
    "switzerland": "CH",
    "syria": "SY",
    "são tomé and príncipe": "ST",
    "tahiti": "PF",
    "tajikistan": "TJ",
    "tanzania": "TZ",
    "thailand": "TH",
    "togo": "TG",
    "trinidad and tobago": "TT",
    "tunisia": "TN",
    "turkmenistan": "TM",
    "türkiye": "TR",
    "turkey": "TR",
    "usa": "US",
    "united states": "US",
    "united states of america": "US",
    "uganda": "UG",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "venezuela": "VE",
    "vietnam": "VN",
    "yemen": "YE",
    "zambia": "ZM",
    "zealand": "NZ",
    "zimbabwe": "ZW"
  };

  // UK constituents
  if (lowerName === "england") return "🏴󠁧󠁢󠁥󠁮󠁧󠁿";
  if (lowerName === "scotland") return "🏴󠁧󠁢󠁳󠁣󠁴󠁿";
  if (lowerName === "wales") return "🏴󠁧󠁢󠁷󠁬󠁳󠁿";
  if (lowerName === "northern ireland") return "🇬🇧"; // or standard GB

  const code = nameToCode[lowerName];
  if (!code) {
    return "⚽"; // Fallback to soccer ball if no flag is found
  }

  const codePoints = code
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}
